---
- name: Test Ansible Playbook
  hosts: azure_vm
  become: yes


  tasks:
    - name: Ensure target directory exists
      file:
        path: "/home/azureuser"
        state: directory
      become: yes

    - name: Copy Python script
      copy:
        src: ../../../web.app/script.py
        dest: /home/azureuser/script.py

    - name: Update system packages
      apt:
        name: '*'
        state: latest
      
    - name: Install Python packages
      apt:
        name:
          - python3
          - python3-pip
          - python3-dev
          - libjpeg-dev
        state: present

    - name: Install Python Packages
      pip:
        name:
          - Flask
          - pillow
          - numpy
          - keras

    # - name: Execute Python script
    #   command: "python3 /home/azureuser/script.py"
    #   async: 600
    #   poll: 0
    #   become: yes
