---
- name: Test Ansible Playbook
  hosts: "{{ lookup('env', 'AZURE_VM_IP') }}"
  become: yes
  gather_facts: no

  tasks:
    - name: Ensure target directory exists
      file:
        path: "/home/azureuser"
        state: directory
      become: yes

    - name: Copy Python script
      copy:
        src: ../../../web.app/script.py
        dest: "/home/azureuser/script.py"
      become: yes
      
    - name: Install Python
      become: yes
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip
        - python3-dev
        - libjpeg-dev

    - name: Install Python Packages
      pip:
        name:
          - Flask
          - pillow
          - numpy
          - keras

    - name: Execute Python script
      command: "python3 /home/azureuser/script.py"
      async: 600
      poll: 0
      become: yes
