---
- name: Test Ansible Playbook
  hosts: azure_vm
  become: yes
  gather_facts: no

  tasks:
    - name: Ensure target directory exists
      file:
        path: "/home/azureuser"
        state: directory
      become: yes

    - name: Copy Python script
      copy:
        src: ../../../web.app/script.py
        dest: "/home/azureuser/script.py"
      become: yes
    - name: Install Python
      raw: sudo apt-get -y update && apt-get install -y python3

    - name: Execute Python script
      command: "python3 /home/azureuser/script.py"
      become: yes
