---
- name: Deploy Java Web App on Azure VM
  hosts: azure_vm
  become: yes
  vars:
    app_directory: /var/www/java_web_app
    ssh_private_key: "{{ secrets.SSH_PRIVATE_KEY }}"
    azure_vm_ip: "{{ secrets.AZURE_VM_IP }}"
    azure_vm_user: "{{ secrets.AZURE_VM_USER }}"

  tasks:
    - name: Ensure target directory exists
      file:
        path: "{{ app_directory }}"
        state: directory
      become: yes

    - name: Copy Java web application
      copy:
        src: your-repo/web_app
        dest: "{{ app_directory }}"
      become: yes

    - name: Install OpenJDK
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Start the Java application
      command: "java -jar {{ app_directory }}/your_app.jar &"
      async: 1000
      poll: 0
      become: yes

    # Additional tasks as needed
