name: Test Ansible Playbook

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:   
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Log in to Docker Hub
        env:
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo ${{ env.password }} | docker login -u ${{ env.username }} --password-stdin

      - name: Build the docker image
        run: |
           docker build . -t alikhan0/onlinebookstore:latest -f ./Docker-files/app/Dockerfile
           docker build . -t alikhan0/mysqldb:latest -f ./Docker-files/db/Dockerfile
          
      - name: push Docker image
        run: |
          docker push alikhan0/onlinebookstore:latest
          docker push alikhan0/mysqldb:latest
    
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Python and Ansible
        run: |
          sudo apt-add-repository ppa:ansible/ansible
          sudo apt update
          sudo apt install ansible

      - name: Deploy with Ansible
        run: ansible-playbook -i ip.txt -u "ec2-user" --private-key ~/.ssh/id_rsa ansible-playbook.yml
        env:
          ANSIBLE_SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
