name: Test Ansible Playbook

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up Ansible
        run: |
          sudo apt -y update
          sudo apt -y install ansible
          
      - name: Check Ansible Version
        run: ansible --version

        
      - name: Establish SSH Connection to Azure VM
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_IP }}
        env:
          AZURE_VM_IP: ${{ secrets.AZURE_VM_IP }}
          AZURE_VM_USER: ${{ secrets.AZURE_VM_USER }}
          
      - name: Debug Environment Variables
        run: |
          echo "AZURE_VM_IP: ${{ secrets.AZURE_VM_IP }}"
          echo "AZURE_VM_USER: ${{ secrets.AZURE_VM_USER }}"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          AZURE_VM_IP: ${{ secrets.AZURE_VM_IP }}
          AZURE_VM_USER: ${{ secrets.AZURE_VM_USER }}
      
      - name: Debug Contents of hosts.ini
        run: cat ansible/hosts.ini

      # - name: Run Ansible Playbook
      #   run: |
      #     cd ansible
      #     ansible-playbook -i hosts.ini playbooks/dep.yml -e "ansible_ssh_private_key_file=$HOME/.ssh/id_rsa" -e "azure_vm_ip=${{ secrets.AZURE_VM_IP }}" -e "azure_vm_user=${{ secrets.AZURE_VM_USER }}"l
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      #     AZURE_VM_IP: ${{ secrets.AZURE_VM_IP }}
      #     AZURE_VM_USER: ${{ secrets.AZURE_VM_USER }}

      - name: Run Ansible Playbook
        run: |
          cd ansible
          ansible-playbook -i hosts.ini playbooks/dep.yml -e "PLACEHOLDER_USER=${{ secrets.AZURE_VM_USER }}" -e "PLACEHOLDER_PRIVATE_KEY=${{ secrets.SSH_PRIVATE_KEY }}" -e "azure_vm_ip=${{ secrets.AZURE_VM_IP }}"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          AZURE_VM_IP: ${{ secrets.AZURE_VM_IP }}
          AZURE_VM_USER: ${{ secrets.AZURE_VM_USER }}

