name: Test Ansible Playbook

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Python and Ansible
        run: |
          sudo apt-add-repository ppa:ansible/ansible
          sudo apt update
          sudo apt install ansible
          sudo chmod 777 /etc/ansible/ansible.cfg
          sudo cat ansible.cfg > /etc/ansible/ansible.cfg
          cat /etc/ansible/ansible.cfg

      - name: Deploy with Ansible
        run: ansible-playbook -i "52.72.161.189" -u "ec2-user" --private-key ~/.ssh/id_rsa ansible-playbook.yml
        env:
          ANSIBLE_SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
